### ISSUE TITLE
Clearing an `input`?

### ISSUE THREAD

**Issue by winny-** [Bogdanp/racket-gui-easy#12]
GUI easy is really nice, being new to reactive programming, it somehow feels intuitive, so I think the design is quite user friendly!

On to the question I had- I ran into a curious behavior  using the `input` UI element.  Using the following code sample, when I type return, the input box text remains the same, though the observable the input box I think is observing has been cleared.  Is there something different I could try?

Thanks!

```
$ racket --version
Welcome to Racket v8.4 [cs].
```

```racket
#lang racket

(require racket/gui/easy
         racket/gui/easy/operator)

(define/obs @input "")

(define/obs @message "Type return to send a message")

(render
 (window
  (text @message)
  (input @input
         (λ (kind s)
           (when (symbol=? kind 'return)
             (:= @message (string-append "You typed: " s))
             (:= @input "")))))) ; Input box still shows text after updating this observable.
```

**Comment by Bogdanp** [comment]
Input fields are somewhat hard to fit into this model and the library needs to do some of its own state tracking to make various cases work as the user expects. The problem here is the input [only changes its contents when the underlying value of the observable changes](https://github.com/Bogdanp/racket-gui-easy/blob/a752c7190a2ced220669d2b894082be91dbefe28/gui-easy-lib/gui/easy/private/view/input.rkt#L83). In your case, the value of `@input` is always `""`, so that never happens. If you change your code to modify the input on change, then things should work as expected:

```racket
(render
 (window
  (text @message)
  (input @input
         (λ (kind s)
           (:= @input s) ;; change the input
           (when (symbol=? kind 'return)
             (:= @message (string-append "You typed: " s))
             (:= @input ""))))))
```

That said, you shouldn't have to do this, so I'm going to leave this issue open while I think of a way to improve `input`. One solution might be to special-case clearing the input, in which case your original code would work fine, but that wouldn't cover other cases.
